In [6]:
import os, sys
user_home = os.environ['HOME']
repo_dir = os.path.join(user_home, 'Documents/git/stoic2021')
sys.path.append(repo_dir)
# print(user_home)
print(sys.path)

from mmdet.datasets.transform4med.load_dicom import *
from mmdet.datasets.transform4med.io4med import IO4Nii
from scripts.visual_func import plot2Image, plotNImage


['/Users/monolith/Documents/git/stoic2021/scripts', '/Users/monolith/miniconda3/lib/python38.zip', '/Users/monolith/miniconda3/lib/python3.8', '/Users/monolith/miniconda3/lib/python3.8/lib-dynload', '', '/Users/monolith/miniconda3/lib/python3.8/site-packages', '/Users/monolith/Documents/git/mmaction2', '/Users/monolith/Documents/git/nnDetection', '/Users/monolith/.local/lib/python3.8/site-packages', '/Users/monolith/Documents/git/stoic2021', '/Users/monolith/miniconda3/lib/python3.8/site-packages/itk/Configuration/..', '/Users/monolith/miniconda3/lib/python3.8/site-packages/itk/Configuration/../../lib', '/Users/monolith/Documents/git/stoic2021']


In [7]:
data_dir = Path('/Users/monolith/Desktop/leg_seg/leg_nii')
test_pid = 'case_leg_dicom_PET084053-NAF_1.2.156.112605.189250940724405.210325230838.3.5184.916816.nii.gz'

pid_fp = data_dir/test_pid
image_3d, af_mat = IO4Nii.read(pid_fp)

NIBABEL


[IO4Nii] affine raw
 [[-9.7656250e-01  0.0000000e+00  0.0000000e+00  2.4951172e+02]
 [ 0.0000000e+00 -9.7656250e-01  0.0000000e+00  2.4951172e+02]
 [ 0.0000000e+00  0.0000000e+00  1.5000000e+00 -1.4516595e+03]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[IO4Nii] affine xyz
 [[-9.7656202e-01  0.0000000e+00  0.0000000e+00  2.4951172e+02]
 [ 0.0000000e+00 -9.7656202e-01  0.0000000e+00  2.4951172e+02]
 [ 0.0000000e+00  0.0000000e+00  1.5000000e+00 -1.4516595e+03]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[IO4Nii] xyz dim index [0, 1, 2]
[IO4Nii] xyz sign [1, 1, 1]
[IO4Nii] image raw <class 'numpy.ndarray'> float64 (512, 512, 201) -1023.0 1779.0
[IO4Nii] image xyz <class 'numpy.ndarray'> float64 (512, 512, 201) -1023.0 1779.0


{'origin': (-249.511719, -249.511719, -1413.23462), 'direction': (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0), 'spacing_dim0': 0.9765625, 'spacing_dim1': 0.9765625, 'spacing_dim2': 1.500000134199134, 'size_dim0': 512, 'size_dim1': 512, 'size_dim2': 463, 'series_name': '1.2.156.112605.189250940724405.201211062827.3.5140.11785'}
